nav:
  enable: true
  travelling: true
  clock: false
  menu:
    - title: æˆ‘çš„
      item:
        - name: éŸ³ä¹é¦†
          link: https://music.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/2201/PNG/96/apple_music_android_logo_icon_134021.png
        - name: MIKUTAP
          link: https://mikutap.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/605/PNG/512/heart-rhythm_icon-icons.com_56083.png
        - name: è¡¨æƒ…ä¸€è§ˆ
          link: https://emoji-show.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/2645/PNG/512/emoji_smile_icon_160172.png
        - name: Cover
          link: https://cover.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/390/PNG/512/book-cover_39346.png

menu:
  æ–‡ç« :
    åˆ†ç±»: /categories/ || anzhiyu-icon-shapes
    æ ‡ç­¾: /tags/ || anzhiyu-icon-tags

  æˆ‘çš„:
    é—²è¨€ç¢è¯­: /essay/ || anzhiyu-icon-lightbulb
    ç•™è¨€æ¿: /comments/ || anzhiyu-icon-envelope

  ç©è€:
    å°ç©ºè°ƒ: /air-conditioner/ || anzhiyu-icon-fan
    E-æœ¨é±¼: /electron-fish/ || fa-solid fa-fish

  æœ¬ç«™:
    å…³äºæœ¬äºº: /about/ || anzhiyu-icon-paper-plane
    éšä¾¿é€›é€›: javascript:toRandomPost() || fa-solid fa-shoe-prints

highlight_theme: mac light
highlight_copy: true
highlight_shrink: false
highlight_height_limit: 300

# ä½œè€…å¡ç‰‡ çŠ¶æ€
author_status:
  enable: true
  statusImg: ""
  skills:
    - æ¸…é£è·ƒçª—å°
    - æ˜ç‰æŒ‚é“¶å¸¦
    - èº«å±…æœ€é«˜å±‚
    - ä¾§èººæŠŠæ˜Ÿæ‘˜

# æ ‡ç­¾å–èŒ
diytitle:
  enable: false
  leaveTitle: w(ï¾ŸĞ”ï¾Ÿ)w ä¸è¦èµ°ï¼å†çœ‹çœ‹å˜›ï¼
  backTitle: â™ª(^âˆ‡^*)æ¬¢è¿è‚¥æ¥ï¼

# æ‰“èµäºŒç»´ç 
reward:
  enable: true
  coinAudio: https://cdn.cbd.int/luoh-blog-static@0.0.5/audio/aowu.m4a
  QR_code:
    - img: https://cdn.cbd.int/luoh-blog-static@0.0.5/image/qrcode-wechat.png
      link:
      text: wechat

# æ¬¢è¿è¯­é…ç½®
greetingBox:
  enable: false
  default: æ™šä¸Šå¥½ğŸ‘‹
  list:
    - greeting: æ™šå®‰ğŸ˜´
      startTime: 0
      endTime: 5
    - greeting: æ—©ä¸Šå¥½é¸­ğŸ‘‹, ç¥ä½ ä¸€å¤©å¥½å¿ƒæƒ…ï¼
      startTime: 6
      endTime: 9
    - greeting: ä¸Šåˆå¥½ğŸ‘‹, çŠ¶æ€å¾ˆå¥½ï¼Œé¼“åŠ±ä¸€ä¸‹ï½
      startTime: 10
      endTime: 10
    - greeting: 11ç‚¹å¤šå•¦, åœ¨åšæŒä¸€ä¸‹å°±åƒé¥­å•¦ï½
      startTime: 11
      endTime: 11
    - greeting: åˆå®‰ğŸ‘‹, å®è´
      startTime: 12
      endTime: 14
    - greeting: ğŸŒˆå……å®çš„ä¸€å¤©è¾›è‹¦å•¦ï¼
      startTime: 14
      endTime: 18
    - greeting: 19ç‚¹å–½, å¥–åŠ±ä¸€é¡¿ä¸°ç››çš„å¤§é¤å§ğŸ”ã€‚
      startTime: 19
      endTime: 19
    - greeting: æ™šä¸Šå¥½ğŸ‘‹, åœ¨å±äºè‡ªå·±çš„æ—¶é—´å¥½å¥½æ”¾æ¾ğŸ˜Œ~
      startTime: 20
      endTime: 24  

# åŠ¨æ•ˆ
dynamicEffect:
  postTopWave: true
  postTopRollZoomInfo: true
  pageCommentsRollZoom: true

runtimeshow:
  enable: true
  publish_date: 4/23/2024 00:00:00

# A simple 404 page
error_404:
  enable: true
  subtitle: "æ€ªå…½æŠŠé¡µé¢æ‹–èµ°äº†..."
  background: https://cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/404.gif #https://pic.chino.my.to/i/2024/07/31/448691.gif

icons:
  fontawesome: true

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover: 

social:
  Github: https://github.com/enlt  anzhiyu-icon-github
  Telegram: https://t.me/zlorix  anzhiyu-icon-telegram  
  QQ: mqqwpa://im/chat?chat_type=wpa&uin=1412219758  anzhiyu-icon-qq

post_meta:
  page:
    date_type: created
    date_format: relative
    categories: true
    tags: true
    label: true
  post:
    date_type: boht
    date_format: relative
    categories: true 
    tags: true
    label: true 

post_copyright:
  enable: true
  decode: false
  author_href:
  location: ä¸­å›½
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

related_post:
  enable: true
  limit: 3
  date_type: created

translate:
  enable: false
  default: ç¹
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: "ç¹"
  msgToSimplifiedChinese: "ç®€"

readmode: false

aside:
  enable: true               # æ˜¯å¦å¯ç”¨ä¾§è¾¹æ 
  hide: false                # æ˜¯å¦éšè—ä¾§è¾¹æ 
  button: true               # æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ æŒ‰é’®
  mobile: true               # æ˜¯å¦åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šæ˜¾ç¤ºä¾§è¾¹æ 
  position: right            # ä¾§è¾¹æ ä½ç½®ï¼Œleft æˆ– right
  display:                   # æ§åˆ¶å¯¹åº”è¯¦æƒ…é¡µé¢æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ 
    archive: true            # æ˜¯å¦åœ¨å½’æ¡£é¡µé¢æ˜¾ç¤º
    tag: true                # æ˜¯å¦åœ¨æ ‡ç­¾é¡µé¢æ˜¾ç¤º
    category: true           # æ˜¯å¦åœ¨åˆ†ç±»é¡µé¢æ˜¾ç¤º
  card_author:
    enable: true           # æ˜¯å¦å¯ç”¨ä½œè€…å¡ç‰‡
    description: æ¸…é£è·ƒçª—å°<br>æ˜ç‰æŒ‚é“¶å¸¦<br>èº«å±…æœ€é«˜å±‚<br>ä¾§èººæŠŠæ˜Ÿæ‘˜
    name_link: /about        # ä½œè€…é“¾æ¥
  card_announcement:
    enable: true
    content: æ¨èä½¿ç”¨Edgeæµè§ˆå™¨è®¿é—®æœ¬ç«™ # <img src='https://api.luoh.my.to/daysign.php'>   # å…¬å‘Šå†…å®¹
  card_weixin:
    enable: false             # æ˜¯å¦å¯ç”¨å¾®ä¿¡å¡ç‰‡
    face:      # æ­£é¢å›¾ç‰‡é“¾æ¥
    backFace: # èƒŒé¢å›¾ç‰‡é“¾æ¥
  card_recent_post:
    enable: false             # æ˜¯å¦å¯ç”¨æœ€æ–°æ–‡ç« å¡ç‰‡
    limit: 9                 # æ˜¾ç¤ºæ–‡ç« æ•°é‡ï¼Œè®¾ç½®ä¸º0åˆ™æ˜¾ç¤ºå…¨éƒ¨
    sort: date               # æ’åºæ–¹å¼ï¼Œdate æˆ– updated
    sort_order:              # æ’åºé¡ºåºï¼Œä¸è¦ä¿®æ”¹è¿™ä¸ªè®¾ç½®é™¤éä½ çŸ¥é“å®ƒæ˜¯å¦‚ä½•å·¥ä½œçš„
  card_categories:
    enable: false            # æ˜¯å¦å¯ç”¨åˆ†ç±»å¡ç‰‡
    limit: 8                 # æ˜¾ç¤ºåˆ†ç±»æ•°é‡ï¼Œè®¾ç½®ä¸º0åˆ™æ˜¾ç¤ºå…¨éƒ¨
    expand: none             # å±•å¼€æ–¹å¼ï¼Œnone/true/false
    sort_order:              # æ’åºé¡ºåºï¼Œä¸è¦ä¿®æ”¹è¿™ä¸ªè®¾ç½®é™¤éä½ çŸ¥é“å®ƒæ˜¯å¦‚ä½•å·¥ä½œçš„
  card_tags:
    enable: true             # æ˜¯å¦å¯ç”¨æ ‡ç­¾å¡ç‰‡
    limit: 40                # æ˜¾ç¤ºæ ‡ç­¾æ•°é‡ï¼Œè®¾ç½®ä¸º0åˆ™æ˜¾ç¤ºå…¨éƒ¨
    color: true             # æ˜¯å¦ä½¿ç”¨é¢œè‰²
    sort_order:              # æ’åºé¡ºåºï¼Œä¸è¦ä¿®æ”¹è¿™ä¸ªè®¾ç½®é™¤éä½ çŸ¥é“å®ƒæ˜¯å¦‚ä½•å·¥ä½œçš„
    highlightTags:           # é«˜äº®æ ‡ç­¾
  card_archives:
    enable: true             # æ˜¯å¦å¯ç”¨å½’æ¡£å¡ç‰‡
    type: monthly            # å½’æ¡£ç±»å‹ï¼Œyearly æˆ– monthly
    format: MMMM YYYY        # æ ¼å¼ï¼Œä¾‹å¦‚ï¼šYYYYå¹´MMæœˆ
    order: -1                # æ’åºæ–¹å¼ï¼Œ1è¡¨ç¤ºå‡åºï¼Œ-1è¡¨ç¤ºé™åº
    limit: 8                 # æ˜¾ç¤ºæ•°é‡ï¼Œè®¾ç½®ä¸º0åˆ™æ˜¾ç¤ºå…¨éƒ¨
    sort_order:              # æ’åºé¡ºåºï¼Œä¸è¦ä¿®æ”¹è¿™ä¸ªè®¾ç½®é™¤éä½ çŸ¥é“å®ƒæ˜¯å¦‚ä½•å·¥ä½œçš„
  card_webinfo:
    enable: true             # æ˜¯å¦å¯ç”¨ç½‘ç«™ä¿¡æ¯å¡ç‰‡
    post_count: true         # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« è®¡æ•°
    last_push_date: false    # æ˜¯å¦æ˜¾ç¤ºæœ€åæ¨é€æ—¥æœŸ
    sort_order:              # æ’åºé¡ºåºï¼Œä¸è¦ä¿®æ”¹è¿™ä¸ªè®¾ç½®é™¤éä½ çŸ¥é“å®ƒæ˜¯å¦‚ä½•å·¥ä½œçš„

pangu:
  enable: true
  field: post

comments:
  use: Twikoo
  text: true
  lazyload: false
  count: true
  card_post_count: false

twikoo:
  envId: https://enltic-twikoo.hf.space/
  region: ap-shanghai
  visitor: false  
  option:
  
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
  
# waline:
  # serverURL: https://waline-five-sand.vercel.app/ui/login# Waline server address url
  # bg: # waline background
  # pageview: false
  # option:  

# Loading Animation (åŠ è½½åŠ¨ç”»)
preloader:
  enable: true
  source: 3
  pace_css_url:
  avatar: https://i1.wp.com/cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/avatar.gif #https://cravatar.cn/avatar/7bd408da64452102b343f062e9f091c0

# è¯„è®ºåŒ¿åé‚®ç®±
visitorMail:
  enable: true
  mail: visitor@luo.to

fancybox: true
#medium_zoom: true

# å¿«æ·é”®é…ç½®
shortcutKey:
  enable: true
  delay: 100 # æ‰€æœ‰é”®ä½å»¶æ—¶è§¦å‘è€Œä¸æ˜¯ç«‹å³è§¦å‘ï¼ˆåŒ…æ‹¬shiftï¼Œä»¥è§£å†³å’Œæµè§ˆå™¨é”®ä½å†²çªé—®é¢˜ï¼‰
  shiftDelay: 200 # shiftæŒ‰ä¸‹å»¶æ—¶å¤šä¹…å¼€å¯  

# å³é”®èœå•
rightClickMenu:
  enable: true

# éšä¾¿é€›é€›peopleæ¨¡å¼
peoplecanvas:
  enable: false
  img:

home_top:
  enable: true # å¼€å…³
  timemode: date #date/updated
  title: ä¸€ç¼•çº¢çº¿è½äººé—´
  subTitle: åŠå£¶æ¸…é…’ç ´ä¸‰å¼¦
  siteText: ä»…æœ›å¾—å›æ¬¢
  category:
    - name: æ•™ç¨‹
      path: /categories/æ•™ç¨‹/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-dove
    - name: æŠ€æœ¯
      path: /categories/æŠ€æœ¯/
      shadow: var(--anzhiyu-shadow-red)
      class: red
      icon: anzhiyu-icon-fire
    - name: ç”Ÿæ´»
      path: /categories/ç”Ÿæ´»/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-book
  default_descr: ä¸‡å†›äº‰æˆ˜äºä¸–é—´
  swiper:
    enable: false
    swiper_css: https://cdn.cbd.int/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper cssä¾èµ–
    swiper_js: https://cdn.cbd.int/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper jsä¾èµ–
  banner:
    tips: TOP
    title: èŠ±é—´ä¸€å£¶é…’ï¼Œå‰‘å®¢äºåƒç§‹ã€‚
    image: https://cdn.cbd.int/luoh-blog-static@0.0.8/image/webp/banner-image.webp #https://cdn.jsdmirror.com/gh/snxdm/picgo@main/2024/1722229480952.webp
    link: https://luoh.pages.dev/

agreementPopup:
  enable: true
  url: /privacy

cloudflare_analytics: 902ecdcc7f2347fca972213c3688b1ac
# google_analytics: G-8NY3DHQBJB

nav_music:
  enable: false
  console_widescreen_music: false
  id: 9216803294
  server: tencent
  all_playlist: https://y.qq.com/n/ryqq/playlist/9216803294

# CDN
# éå¿…è¦è¯·ä¸è¦ä¿®æ”¹
CDN:
  internal_provider: cbd
  third_party_provider: cbd
  option:
    meting_api: https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r
    twikoo: https://cdn.cbd.int/twikoo@1.6.39/dist/twikoo.all.min.js
    busuanzi: https://cdn.cbd.int/penndu@1.0.0/bsz.js

# dark mode
darkmode:
  enable: true
  button: true
  autoChangeMode: 1
  start: 8
  end: 22

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq #æƒ³è¦æ˜¾ç¤ºçš„å†…å®¹  
  
# åŒæ æ–‡ç« 
article_double_row: true

mourn:
  enable: true
  days: [4-4, 7-7, 9-18, 12-13]

avatar:
  img: https://i1.wp.com/cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/avatar.gif #https://cravatar.cn/avatar/7bd408da64452102b343f062e9f091c0
  effect: false

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false # for post

mainTone:
  enable: true
  mode: api 
  api: https://api.qjqq.cn/api/Imgcolor?img=
  cover_change: true

# ç•™è¨€å¼¹å¹•é…ç½®
# comment_barrage_config:
  # enable: true
  # maxBarrage: 1
  # barrageTime: 8000
  # accessToken: "8a7ef65d0a45454fb3e170149f5f9f1a"
  # mailMd5: "4304d02503b34d3d8b7bfd123ccfc9fc"

# Footer Settings
footer:
  owner:
    enable: true
    since: 2023
  custom_text:
  runtime:
    enable: false
    launch_time: 04/23/2024 00:00:00 # ç½‘ç«™ä¸Šçº¿æ—¶é—´
    work_img: https://cdn.cbd.int/luoh-blog-static@0.0.1/image/è½æ¸ç¦»-è‹¦é€¼å­¦ç”Ÿè€….svg
    work_description: åœ¨ä¸‹ä¹ƒè‹¦é€¼å­¦ç”Ÿè€…
    offduty_img: https://cdn.cbd.int/luoh-blog-static@0.0.1/image/è½æ¸ç¦»-è‹¦é€¼å­¦ç”Ÿè€….svg
    offduty_description: åœ¨ä¸‹ä¹ƒè‹¦é€¼å­¦ç”Ÿè€…
  # å¾½æ ‡éƒ¨åˆ†é…ç½®é¡¹
  bdageitem:
    enable: true
    list:
      - link: https://hexo.io/ #å¾½æ ‡æŒ‡å‘ç½‘ç«™é“¾æ¥
        shields: https://cdn.cbd.int/anzhiyu-blog@2.1.5/img/badge/Frame-Hexo.svg #å¾½æ ‡API
        message: åšå®¢æ¡†æ¶ä¸ºHexo #å¾½æ ‡æç¤ºè¯­
      - link: https://cdn.cbd.int/
        shields: https://cdn.cbd.int/luoh-blog-static@0.1.4-rc.2/image/svg/CDN-Unpkg-green.svg
        message: æœ¬ç«™ä½¿ç”¨Unpkgä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ
      - link: https://github.com/
        shields: https://cdn.cbd.int/anzhiyu-blog@2.1.5/img/badge/Source-Github.svg
        message: æœ¬ç«™é¡¹ç›®ç”±Githubæ‰˜ç®¡
      - link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
        shields: https://cdn.cbd.int/anzhiyu-theme-static@1.0.9/img/Theme-AnZhiYu-2E67D3.svg
        message: æœ¬ç«™ä½¿ç”¨AnZhiYuä¸»é¢˜
      - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
        shields: https://cdn.cbd.int/anzhiyu-blog@2.2.0/img/badge/Copyright-BY-NC-SA.svg
        message: æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯
  socialBar:
    enable: false
  list:
    enable: true
    randomFriends: 0
    project:
      - title: æœåŠ¡
        links:
          - title: ä¸è’œå­
            link: https://dusays.com/476/
          - title: Unpkg
            link: https://cdn.cbd.int/
          - title: luohAPI
            link: https://api.luoh.my.to/
      - title: å¯¼èˆª
        links:
          - title: å³åˆ»çŸ­æ–‡
            link: /essay/
          - title: éšå¬éŸ³ä¹
            link: https://music.luoh.pages.dev/
          - title: ç•™è¨€æ¿
            link: /comments/
      - title: åè®®
        links:
          - title: éšç§åè®®
            link: /privacy/
          - title: Cookies
            link: /cookies/
          - title: ç‰ˆæƒåè®®
            link: /copyright/
  footerBar:
    enable: true
    cc:
      enable: true
    linkList:
      - link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
        text: ä¸»é¢˜

# 51aç»Ÿè®¡é…ç½®
LA:
  enable: false
  ck: # 3J4jpflGza04donK
  LingQueMonitorID: # 3JBt9UjSP6o0Fuqu

local_search:
  enable: true
  preload: true
  CDN:

theme_color:                   # ä¸»é¢˜é¢œè‰²é…ç½®çš„å¼€å§‹
  enable: true                 # å¯ç”¨ä¸»é¢˜é¢œè‰²åŠŸèƒ½
  main: "#425AEF"              # ä¸»è¦çš„é¢œè‰²ï¼Œç”¨äºçªå‡ºæ˜¾ç¤ºå’ŒæŒ‰é’®ç­‰é‡è¦å…ƒç´ 
  dark_main: "#a5bda2"         # æš—è‰²æ¨¡å¼ä¸‹çš„ä¸»è¦é¢œè‰²
  paginator: "#425AEF"         # åˆ†é¡µå™¨ï¼ˆå¦‚é¡µé¢å¯¼èˆªï¼‰çš„é¢œè‰²
  # button_hover: "#FF7242"     # é¼ æ ‡æ‚¬åœåœ¨æŒ‰é’®ä¸Šæ—¶çš„é¢œè‰²ï¼Œè¿™é‡Œè¢«æ³¨é‡Šæ‰äº†ï¼Œè¡¨ç¤ºä¸ä½¿ç”¨
  text_selection: "#2128bd"    # æ–‡æœ¬é€‰ä¸­æ—¶çš„èƒŒæ™¯é¢œè‰²
  link_color: "var(--anzhiyu-fontcolor)" # é“¾æ¥çš„é¢œè‰²ï¼Œä½¿ç”¨é¢„å®šä¹‰çš„å˜é‡
  meta_color: "var(--anzhiyu-fontcolor)" # å…ƒæ•°æ®ï¼ˆå¦‚æ—¥æœŸã€ä½œè€…ä¿¡æ¯ï¼‰çš„é¢œè‰²
  hr_color: "#4259ef23"        # æ°´å¹³çº¿ï¼ˆåˆ†éš”çº¿ï¼‰çš„é¢œè‰²
  code_foreground: "#fff"     # ä»£ç å—ä¸­çš„æ–‡å­—é¢œè‰²
  code_background: "var(--anzhiyu-code-stress)" # ä»£ç å—çš„èƒŒæ™¯é¢œè‰²
  toc_color: "#425AEF"         # ç›®å½•ï¼ˆTable of Contentsï¼‰çš„é¢œè‰²
  # blockquote_padding_color: "#425AEF" # å¼•ç”¨å—çš„å†…è¾¹è·é¢œè‰²ï¼Œè¿™é‡Œè¢«æ³¨é‡Šæ‰äº†
  # blockquote_background_color: "#425AEF" # å¼•ç”¨å—çš„èƒŒæ™¯é¢œè‰²ï¼Œè¿™é‡Œä¹Ÿè¢«æ³¨é‡Šæ‰äº†
  scrollbar_color: "var(--anzhiyu-scrollbar)" # æ»šåŠ¨æ¡çš„é¢œè‰²
  meta_theme_color_light: "#f7f9fe" # å…ƒæ•°æ®åœ¨äº®è‰²æ¨¡å¼ä¸‹çš„èƒŒæ™¯é¢œè‰²
  meta_theme_color_dark: "#18171d"  # å…ƒæ•°æ®åœ¨æš—è‰²æ¨¡å¼ä¸‹çš„èƒŒæ™¯é¢œè‰²  
  
inject:
  head:
    - <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.1.3-rc.1/css/font.css"> # å­—ä½“
    - <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/home.css"> # é¦–é¡µæ–‡ç« å¡ç‰‡æ“¦äº®æ•ˆæœ
    #- <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/welcome.css"> # ä¸ªæ€§å®šä½æ¬¢è¿
    #- <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/custom.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="https://cdn.cbd.int/cn-fontsource-lxgw-wen-kai-gb-screen/font.css"></link>
  bottom:
    - <script type="text/javascript" src="https://unpkg.zhimg.com/jquery@latest/dist/jquery.min.js"></script> # jquery.min.js
    #- <script defer="true" src="https://cdn.cbd.int/luoh-blog-static@0.0.2/js/welcome.js"></script> # ä¸ªæ€§å®šä½æ¬¢è¿ä¿¡æ¯
    #- <script async data-pjax src="https://cdn.cbd.int/luoh-blog-static@0.0.2/js/imgloaded.js?1"></script> # é¦–é¡µå›¾ç‰‡æ¸è¿›å¼åŠ è½½
lazyload:
  enable: true
  field: post
  placeholder: https://cdn.cbd.int/luoh-blog-static@0.1.4-rc.5/image/gif/loading.gif
  blur: true
  progressive: true
  extend:
    page: true

# ä¸­æ§å°
centerConsole:
  enable: false
  card_tags:
    enable: false
  card_archives:
    enable: false
    
# ptool æ–‡ç« åº•éƒ¨å·¥å…·
ptool:
  enable: true
  share_mobile: true
  share_weibo: true
  share_copyurl: true
  categories: false # æ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
  mode: # è¿è¥æ¨¡å¼ä¸è´£ä»»ï¼Œä¸é…ç½®ä¸æ˜¾ç¤º

# æ–‡ç« é¡¶éƒ¨aiæ‘˜è¦
post_head_ai_description:
  enable: true
  gptName: LuoH
  mode: local # é»˜è®¤æ¨¡å¼ å¯é€‰å€¼: tianli/local
  switchBtn: false # å¯ä»¥é…ç½®æ˜¯å¦æ˜¾ç¤ºåˆ‡æ¢æŒ‰é’® ä»¥åˆ‡æ¢tianli/local
  btnLink: https://luoh.pages.dev/
  randomNum: 3 # æŒ‰é’®æœ€å¤§çš„éšæœºæ¬¡æ•°ï¼Œä¹Ÿå°±æ˜¯ä¸€ç¯‡æ–‡ç« æœ€å¤§éšæœºå‡ºæ¥å‡ ç§
  basicWordCount: 1000 # æœ€ä½è·å–å­—ç¬¦æ•°, æœ€å°1000, æœ€å¤§1999
  key: x
  Referer: https://xx.xx/